import './globals.css'

export const metadata = {
  title: 'Qoute Generater',
  description: 'Generated by Developer Ubaid',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-gradient-to-r from-violet-500 to-fuchsia-500' >{children}</body>
    </html>
  )
}
